import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Syne } from "next/font/google";
import { BackToTop, ScrollProgress } from "@/components";
import "./globals.css";

const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
  variable: "--font-syne",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Decodex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.variable} ${plusJakartaSans.variable}`}>
        <ScrollProgress />
        <div className="flex min-h-screen flex-col">
          <div className="flex-1">{children}</div>
          <footer className="border-t border-white/10 bg-surface/70 px-4 py-6 backdrop-blur-sm sm:px-6">
            <div className="mx-auto flex w-full max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <p className="font-[var(--font-heading)] text-xl font-extrabold tracking-tight text-icewhite">
                  DecodeX
                </p>
                <p className="mt-1 text-xs text-icewhite/65">
                  Built at AI DecodeX Hackathon 2025
                </p>
              </div>
              <div className="flex items-center gap-3">
                <a
                  href="https://github.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex size-9 items-center justify-center rounded-full border border-white/15 bg-white/[0.03] text-icewhite/75 transition hover:border-amber/60 hover:text-amber"
                  aria-label="GitHub"
                >
                  <svg
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    className="size-4"
                    aria-hidden="true"
                  >
                    <path d="M12 .5a12 12 0 0 0-3.79 23.39c.6.11.82-.26.82-.58v-2.1c-3.34.73-4.04-1.41-4.04-1.41-.55-1.37-1.33-1.73-1.33-1.73-1.09-.72.08-.71.08-.71 1.2.08 1.84 1.23 1.84 1.23 1.08 1.85 2.82 1.31 3.5 1 .11-.78.42-1.31.76-1.61-2.67-.31-5.47-1.34-5.47-5.96 0-1.32.47-2.39 1.23-3.24-.12-.31-.53-1.57.12-3.27 0 0 1-.32 3.3 1.24a11.4 11.4 0 0 1 6 0C17.99 4.6 19 4.92 19 4.92c.65 1.7.24 2.96.12 3.27.77.85 1.23 1.92 1.23 3.24 0 4.64-2.8 5.65-5.48 5.95.43.37.82 1.1.82 2.22v3.29c0 .32.22.69.82.58A12 12 0 0 0 12 .5Z" />
                  </svg>
                </a>
                <span className="inline-flex items-center rounded-full border border-amber/35 bg-amber/10 px-3 py-1 text-[11px] font-medium text-amber">
                  Powered by Claude AI
                </span>
              </div>
            </div>
          </footer>
        </div>
        <BackToTop />
      </body>
    </html>
  );
}
